//! Forecast behaviour: the information cutoff, determinism, contract validity, honesty on
//! thin data, and interval coverage on synthetic data generated by the model's own process.

use koplik_contracts::v1::Forecast;
use koplik_contracts::v3::{
    CaseCount, CaseDefinition, GeoId, MissingReason, MmwrWeek, Provenances, WeeklyCaseCount,
};
use koplik_epi::forecast::{
    ForecastConfig, ForecastError, HUB_QUANTILE_LEVELS, ProjectionStatus, forecast_weekly,
    project_series,
};
use koplik_epi::rt::{InsufficientReason, SerialInterval};
use serde_json::json;

fn prov(tag: &str) -> Provenances {
    serde_json::from_value(json!([{
        "source_id": "synthetic-forecast-test",
        "url": format!("https://example.test/{tag}"),
        "retrieved_at": "2026-09-30T12:00:00Z",
        "sha256": "ab".repeat(32),
        "licence_id": "synthetic"
    }]))
    .unwrap()
}

fn texas() -> GeoId {
    "48".parse().unwrap()
}

fn week(n: u8) -> MmwrWeek {
    MmwrWeek::new(2025, n).unwrap()
}

fn row(geo: GeoId, w: u8, cases: CaseCount) -> WeeklyCaseCount {
    WeeklyCaseCount {
        geography: geo,
        week: week(w),
        cases,
        case_definition: CaseDefinition::Confirmed,
        provenance: prov("a"),
    }
}

fn reported(geo: GeoId, w: u8, count: u32) -> WeeklyCaseCount {
    row(geo, w, CaseCount::Reported { count })
}

/// A small, fast configuration for tests that do not measure coverage.
fn quick() -> ForecastConfig {
    ForecastConfig {
        run_count: 50,
        ..ForecastConfig::default()
    }
}

/// Weeks 1..=12 of a growing outbreak, enough history for the default look-back.
fn history() -> Vec<WeeklyCaseCount> {
    [3, 5, 8, 12, 20, 31, 45, 60, 72, 80, 85, 90]
        .iter()
        .enumerate()
        .map(|(i, &c)| reported(texas(), i as u8 + 1, c))
        .collect()
}

#[test]
fn rows_after_the_origin_never_change_the_forecast() {
    let origin = week(12);
    let base = forecast_weekly(&history(), origin, &quick(), 7).unwrap();
    assert_eq!(base[0].projection.status, ProjectionStatus::Ok);
    assert_eq!(base[0].rows.len(), 8);

    // The same history plus wildly different weeks after the origin.
    let mut with_future = history();
    for w in 13..=20 {
        with_future.push(reported(texas(), w, 5_000));
    }
    let leaked = forecast_weekly(&with_future, origin, &quick(), 7).unwrap();
    assert_eq!(leaked, base);

    // Rows after the origin that are missing or duplicated are not even looked at.
    let mut with_junk = history();
    with_junk.push(row(
        texas(),
        13,
        CaseCount::Missing {
            reason: MissingReason::Suppressed,
        },
    ));
    with_junk.push(reported(texas(), 13, 1));
    assert_eq!(
        forecast_weekly(&with_junk, origin, &quick(), 7).unwrap(),
        base
    );
}

#[test]
fn a_future_row_with_another_case_definition_does_not_change_the_forecast() {
    let origin = week(12);
    let base = forecast_weekly(&history(), origin, &quick(), 7).unwrap();
    let mut rows = history();
    let mut other = reported(texas(), 13, 70);
    other.case_definition = CaseDefinition::ConfirmedOrUnknownStatus;
    rows.push(other);
    assert_eq!(forecast_weekly(&rows, origin, &quick(), 7).unwrap(), base);
    // At or before the origin the definitions must agree.
    let mut rows = history();
    rows[11].case_definition = CaseDefinition::ConfirmedOrUnknownStatus;
    assert!(forecast_weekly(&rows, origin, &quick(), 7).is_err());
}

#[test]
fn a_missing_origin_week_is_insufficient_even_when_later_weeks_exist() {
    let mut rows = history();
    rows.retain(|r| r.week != week(12));
    rows.push(reported(texas(), 13, 95));
    let out = forecast_weekly(&rows, week(12), &quick(), 7).unwrap();
    assert_eq!(
        out[0].projection.status,
        ProjectionStatus::InsufficientData(InsufficientReason::MissingCount)
    );
    assert!(out[0].rows.is_empty());
}

#[test]
fn same_seed_is_bit_identical_and_other_seeds_or_geographies_differ() {
    let a = forecast_weekly(&history(), week(12), &quick(), 7).unwrap();
    let b = forecast_weekly(&history(), week(12), &quick(), 7).unwrap();
    assert_eq!(a, b);
    let c = forecast_weekly(&history(), week(12), &quick(), 8).unwrap();
    assert_ne!(a[0].projection.members, c[0].projection.members);

    let gaines: GeoId = "48165".parse().unwrap();
    let mut both = history();
    both.extend(history().into_iter().map(|mut r| {
        r.geography = gaines;
        r
    }));
    let out = forecast_weekly(&both, week(12), &quick(), 7).unwrap();
    assert_eq!(out.len(), 2);
    assert_eq!(out[0].projection.r_posterior, out[1].projection.r_posterior);
    assert_ne!(out[0].projection.members, out[1].projection.members);
    assert_eq!(out[0].projection.members, a[0].projection.members);
}

#[test]
fn rows_are_valid_v1_forecasts_with_hub_quantiles() {
    let out = forecast_weekly(&history(), week(12), &ForecastConfig::default(), 7).unwrap();
    let rows = &out[0].rows;
    assert_eq!(rows.len(), 8);
    for (i, row) in rows.iter().enumerate() {
        assert_eq!(row.origin_week, week(12));
        assert_eq!(row.target_week, week(13 + i as u8));
        assert_eq!(row.seed, 7);
        assert_eq!(row.run_count, 1_000);
        let levels: Vec<f64> = row.quantiles.iter().map(|q| q.level).collect();
        assert_eq!(levels, HUB_QUANTILE_LEVELS.to_vec());
        // The contract's own validation: monotone quantiles, target after origin.
        // (serde_json's default float parser can differ from the written value by one ulp,
        // so quantile values are compared with a tolerance, everything else exactly.)
        let json = serde_json::to_string(row).unwrap();
        let back: Forecast = serde_json::from_str(&json).unwrap();
        assert_eq!(back.quantiles.len(), row.quantiles.len());
        for (a, b) in back.quantiles.iter().zip(&row.quantiles) {
            assert_eq!(a.level, b.level);
            assert!((a.value - b.value).abs() < 1e-9);
        }
        let back = Forecast {
            quantiles: row.quantiles.clone(),
            ..back
        };
        assert_eq!(&back, row);
    }
    // A growing series (R > 1 over the window) projects upward in the median.
    let median = |r: &Forecast| r.quantiles.iter().find(|q| q.level == 0.5).unwrap().value;
    assert!(median(&rows[7]) > median(&rows[0]));
}

#[test]
fn thin_or_empty_windows_are_insufficient_not_guesses() {
    let cfg = quick();
    // Below the minimum-count threshold (11 over three weeks).
    let few: Vec<Option<u32>> = vec![Some(0), Some(0), Some(0), Some(2), Some(3), Some(4)];
    let p = project_series(&few, texas(), &cfg, 1).unwrap();
    assert_eq!(
        p.status,
        ProjectionStatus::InsufficientData(InsufficientReason::BelowThreshold { cases: 9 })
    );
    assert!(p.members.is_empty() && p.r_posterior.is_none());
    // A window that would include the first step (whose infectivity is undefined).
    let short: Vec<Option<u32>> = vec![Some(30), Some(40), Some(50)];
    let p = project_series(&short, texas(), &cfg, 1).unwrap();
    assert_eq!(
        p.status,
        ProjectionStatus::InsufficientData(InsufficientReason::IncompleteWindow)
    );
    // A look-back reaching before the series is unknown by default.
    let short: Vec<Option<u32>> = vec![Some(30), Some(40), Some(50), Some(60)];
    let p = project_series(&short, texas(), &cfg, 1).unwrap();
    assert_eq!(
        p.status,
        ProjectionStatus::InsufficientData(InsufficientReason::MissingCount)
    );
    // A missing count inside the look-back.
    let gap: Vec<Option<u32>> = vec![Some(30), None, Some(40), Some(50), Some(60), Some(70)];
    let p = project_series(&gap, texas(), &cfg, 1).unwrap();
    assert_eq!(
        p.status,
        ProjectionStatus::InsufficientData(InsufficientReason::MissingCount)
    );
    assert_eq!(
        project_series(&[], texas(), &cfg, 1).unwrap().status,
        ProjectionStatus::InsufficientData(InsufficientReason::IncompleteWindow)
    );
}

#[test]
fn an_exploding_projection_is_refused_not_clipped() {
    let counts: Vec<Option<u32>> = [1, 1, 1, 100, 10_000, 1_000_000]
        .iter()
        .map(|&c| Some(c))
        .collect();
    let err = project_series(&counts, texas(), &quick(), 1).unwrap_err();
    assert!(matches!(err, ForecastError::Overflow { .. }), "{err}");
}

/// Test-only Poisson by inversion (plain `f64`; portability is not at stake here).
fn poisson_inversion(u: f64, mean: f64) -> u32 {
    let mut k = 0_u32;
    let mut p = (-mean).exp();
    let mut cdf = p;
    while u > cdf && k < 100_000 {
        k += 1;
        p *= mean / f64::from(k);
        cdf += p;
    }
    k
}

/// A tiny deterministic uniform generator for the synthetic process (SplitMix64).
struct SplitMix(u64);
impl SplitMix {
    fn uniform(&mut self) -> f64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        ((z >> 11) as f64 + 0.5) / 9_007_199_254_740_992.0
    }
}

/// Interval coverage on synthetic data from the forecast's own generative process: a
/// Poisson renewal with the measles serial interval and a constant `R` per replicate.
/// A correctly specified model with calibrated uncertainty covers about the nominal
/// rate; the tolerances allow for the finite number of replicates and for the `R` window
/// (the posterior sees three weeks, the process is constant).
#[test]
fn intervals_cover_synthetic_truth_at_about_the_nominal_rate() {
    let cfg = ForecastConfig {
        run_count: 300,
        ..ForecastConfig::default()
    };
    let si = SerialInterval::MEASLES
        .discretize_weekly(cfg.max_lag_weeks)
        .unwrap();
    let w = si.weights();
    let replicates = 40_u64;
    let history_weeks = 10_usize;
    let horizon = cfg.horizon_weeks as usize;
    let (mut n, mut in_50, mut in_90) = (0_u32, 0_u32, 0_u32);
    let mut forecast_made = 0_u32;
    for rep in 0..replicates {
        let mut rng = SplitMix(1_000 + rep);
        // R between 0.7 and 1.5, constant for the replicate.
        let r = 0.7 + 0.8 * rng.uniform();
        let mut series: Vec<u32> = vec![40, 40, 40];
        while series.len() < history_weeks + horizon {
            let n_so_far = series.len();
            let mut lambda = 0.0;
            for (k, wk) in w.iter().enumerate().skip(1) {
                if k <= n_so_far {
                    lambda += wk * f64::from(series[n_so_far - k]);
                }
            }
            series.push(poisson_inversion(rng.uniform(), r * lambda));
        }
        let rows: Vec<WeeklyCaseCount> = series[..history_weeks]
            .iter()
            .enumerate()
            .map(|(i, &c)| reported(texas(), i as u8 + 1, c))
            .collect();
        let out = forecast_weekly(&rows, week(history_weeks as u8), &cfg, 99 + rep).unwrap();
        if out[0].projection.status != ProjectionStatus::Ok {
            continue;
        }
        forecast_made += 1;
        for (h, row) in out[0].rows.iter().enumerate() {
            let truth = f64::from(series[history_weeks + h]);
            n += 1;
            let q = |level: f64| {
                row.quantiles
                    .iter()
                    .find(|q| (q.level - level).abs() < 1e-9)
                    .unwrap()
                    .value
            };
            if q(0.25) <= truth && truth <= q(0.75) {
                in_50 += 1;
            }
            if q(0.05) <= truth && truth <= q(0.95) {
                in_90 += 1;
            }
        }
    }
    assert!(
        forecast_made >= 30,
        "only {forecast_made} forecasts were possible"
    );
    let c50 = f64::from(in_50) / f64::from(n);
    let c90 = f64::from(in_90) / f64::from(n);
    assert!((0.38..=0.62).contains(&c50), "50% coverage {c50} over {n}");
    assert!((0.80..=0.97).contains(&c90), "90% coverage {c90} over {n}");
}
